### PR TITLE
Change 'resource' to 'related' in link objects

### PR DESCRIPTION
**Pull request by bintoro**
Based on #425.

### CODE REVIEW

**Comment by bintoro** [comment]
Oh yeah, one of the changes in #425 that wasn't discussed was the removal of one of the [example payloads](https://github.com/json-api/json-api/pull/425#issuecomment-77691523). This PR leaves it intact for now, but I think its utility is pretty questionable.

**Comment by dgeb** [comment]
@bintoro thanks for adding the commit to update the example payloads. We have a few on the home page as well.

**Comment by dgeb** [comment]
> Oh yeah, one of the changes in #425 that wasn't discussed was the removal of one of the example payloads. This PR leaves it intact for now, but I think its utility is pretty questionable.

Let's discuss in a separate issue.

**Comment by bintoro** [comment]
Amended the commit. The paragraph about reserved keys mentions `resource` but  #421 will remove the whole thing.

**Comment by dgeb** [comment]
@bintoro thank you.

@steveklabnik @wycats any objections? I believe this is more than bike-shedding, as explained here https://github.com/json-api/json-api/pull/425#issuecomment-77751291

**Comment by dgeb** [comment]
@bintoro could you please rebase? I merged #399 and now there's a conflict.

**Comment by bintoro** [comment]
Yeah I noticed, it's done now.

**Comment by bintoro** [comment]
Hmm... Looking at this again, I can't decide if

>  [...] even when the relationship (the set of identities of the referenced resources) mutates.

is too much and if

>  [...] even when the relationship (the set of referenced resources) mutates.

would suffice.

The noun "set" already makes it fairly clear that it's about the collection, not the resources themselves mutating. @dgeb, what say you?

**Comment by tkellen** [comment]
Just chiming in to say that I think the latter is sufficient.

**Comment by dgeb** [comment]
I agree with @tkellen - I did find the former phrasing a bit awkward.

**Comment by tkellen** [comment]
I'm :+1: to this change, `related` seems much more appropriate.

**Comment by bintoro** [comment]
Aaaand... amended once more.

**Comment by dgeb** [comment]
Discussed with @wycats and @tkellen - we're all good on this. Thanks @bintoro!

**Pull request merged**
