### PR TITLE
Example with links in linked resources

### PR DESCRIPTION
**Pull request by hesalx**
To shed some light on such questions #314. Because I have met such question at least in one more discussion somewhere.

I had added another example to not increase complexity of the first one.

### CODE REVIEW

**Comment by kurko** [comment]
:+1:

**Comment by dgeb** [comment]
@arantir - This is a great example, although it may not be completely necessary depending on the outcome of #311

Either way, I think that the inclusion of a top-level links example that is based on a linked resource (`"comments.author"` here) is a nice addition.

**Comment by krainboltgreene** [comment]
That feeling when all this time you've confused `links` with `linked`.

Good example.

**Comment by dgeb** [comment]
Thanks for your work here @arantir. Closing due to the simplification of top-level links in #341.

**Pull request closed without merging**
