### PR TITLE
Add .NET JsonApiFramework [Client] and JsonApiFramework [Server] to implementations

### PR DESCRIPTION
**Pull request by scott-mcdonald**
Signed-off-by: Scott McDonald scott@quantumsoft.com

### CODE REVIEW

**Comment by scott-mcdonald** [comment]
GitHub project: https://github.com/scott-mcdonald/JsonApiFramework

**Comment by dgeb** [comment]
@scott-mcdonald would you mind trimming out the phrase "Extreme high code quality with 1,800+ unit tests." in both places that it appears? I appreciate the importance of unit testing but this phrase sounds a bit too much like marketing, and I'd prefer to keep descriptions brief.

**Comment by scott-mcdonald** [comment]
@dgeb understood and I have removed any smell of marketing verbiage. Please review and accept pull request if it meets your standards. Thanks...

**Comment by dgeb** [comment]
Looks good - thanks @scott-mcdonald!

**Pull request merged**
