### PR TITLE
Added favicon.ico

### PR DESCRIPTION
**Pull request by iamsebastian**
Hej guys,

Thanks for your wonderful work.

While I'm creating a new node/Express-API in combination with a Ember app, I always have some pinned tabs open, that points to the jsonapi.org.
Is it possible, that you could add a favicon (this, or another) to your jekyll gh-pages? This would help a lot to see, which tab is jsonapi.org and which tab is another one, without a favicon.

Thanks in advance.

### CODE REVIEW

**Comment by ethanresnick** [comment]
Hey Sebastian!

Thanks for submitting this. I really like the idea of having a favicon, and it seems like an easy usability win.

The icon in your PR, though, doesn't quite stand out enough from the tab bar in my opinion. So, I put together an alternative that has the same basic structure, but uses the JSON:API fonts/colors and has a bit more contrast. That is viewable in the `favicon` branch. I'll give you and the other editors (cc @dgeb) a chance to give any feedback on that before I merge it in.

**Comment by tkellen** [comment]
Thanks a bunch @iamsebastian. I agree with @ethanresnick on this so I am going to give this a close. I really appreciate you taking the time to submit this, though!

**Comment by tkellen** [comment]
Whoops, wrong button! Reverted in #956

**Comment by iamsebastian** [comment]
For sure, my submitted Favicon was just a placeholder, where your Favicon should find a place to be. 
Greets.

**Pull request merged**
