### PR TITLE
Added link to JSONAPI.NET, a .NET implementation of the spec.

### PR DESCRIPTION
**Pull request by SphtKr**
I'm the author of JSONAPI.NET, any questions let me know. Thanks!

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you! Glad to see this :)

**Comment by jonnii** [comment]
@SphtKr I have something that does something similar, it's mainly focused on automatically enveloping json responses: https://github.com/jonnii/emvelope

**Comment by SphtKr** [comment]
@jonnii Hi Jonnii, yes, I just found your project the other day. I found I had to do more than just "wrap" the result, I had to come up with a framework for putting ID values in for related objects, collecting and including related objects (making "Compound Documents"--does emvelope have code for that? I found that was one of the hardest things), and I have some (I think) really cool Entity Framework integration: you can mostly just subclass my EF-specific ApiController and it will already do GET, POST, PUT, and DELETE with no extra code! I see you've got some additional flexibility that I don't, like different case styles. Anyway, I'd be interested in your feedback and/or contributions.

**Comment by jonnii** [comment]
@SphtKr to get full json-api compatibility is certainly not a trivial task and what I've done wouldn't work for that. Right now I can support meta-data (for paging etc...) and just wrapping/unwrapping the envelope. I think ultimately the direction you've gone is the right way, maybe the final solution will be to offer something like https://github.com/WebApiContrib/CollectionJson.Net.

btw, you should also consider moving your code to github...

**Comment by SphtKr** [comment]
@jonnii :-) Yes, I'm already questioning choosing CodePlex…I thought there'd be some value, say integration with NuGet or for documentation generation from code (a la Sandcastle)…but looks like it's not so great, really.

Hmm! I haven't figured out paging yet, I'll have a look at your code.

**Pull request merged**
