### PR TITLE
Reserved members of complex attributes

### PR DESCRIPTION
**Pull request by hhware**
I suggest to turn it to a RFC verb. IMHO, it should be **MUST** instead, but it could be argued that **SHOULD** could be more appropriate.

### CODE REVIEW

**Comment by bintoro** [comment]
Oh yeah, this one. I intentionally used a non-normative word for consistency with other objects. There's no object in the spec for which reserved members are actually formally reserved. I agree they should be, but then this is far from the only case to be considered. And I think the word here needs to be a MUST.

**Comment by hhware** [comment]
> There's no object in the spec for which reserved members are actually formally reserved

@bintoro, sorry, do not quite understand what you mean by it. Is not this a formal reservation:
"A resource object **MUST** contain at least the following top-level members"

> And I think the word here needs to be a MUST.

I also think it should be **MUST**

**Comment by bintoro** [comment]
@hhware I've changed my mind and would be happy to see this PR merged if you could just replace the SHOULD with a MUST. I concluded that the situation's not exactly comparable to the other objects.

**Comment by hhware** [comment]
@bintoro, thanks for reviewing! Updated.

**Comment by tkellen** [comment]
:+1:

**Pull request merged**
