### PR TITLE
disallow links and included if data is missing

### LINKED ISSUE #689: some top-level keys should not be allowed unless primary data is present
The spec currently says:

```
A document's top level **MAY** also have the following members:

* `"jsonapi"`: an object describing the server's implementation
* `"links"`: URLs related to the primary data.
* `"included"`: an array of resource objects that are related to the primary
  data and/or each other ("included resources").

If any of these members appears in the top-level of a response, their values
**MUST** comply with this specification.
```

In cases where `"data"` is absent (i.e. the response contains errors or just plain `"meta"`), then I believe `"included"` and maybe also `"links"` should be disallowed from the top-level. I wasn't able to find any language that stated this explicitly, though maybe I missed something.

### PR DESCRIPTION
**Pull request by csantero**
This closes #689. I would request that this be considered for review before 1.0, since this change will not be possible afterward.

### CODE REVIEW

**Comment by dgeb** [comment]
I'm fine with this requirement. However, I think it should be moved below the next sentence / paragraph so that the phrase "any of these members" in that sentence clearly apply to the full list. 

@csantero - would you mind making this change please?

**Comment by lode** [comment]
Why is a top-level `links` not allowed? Shouldn't that always contain a self link which resulted in this error?

**Comment by dgeb** [comment]
@lode that's a good point - thanks for raising it. Let's leave `links` out of this requirement.

**Comment by csantero** [comment]
@dgeb Updated the diff to only cover `included`, and moved the paragraph.

**Comment by dgeb** [comment]
Great - thanks @csantero!

**Pull request merged**
