### PR TITLE
Site simplifications

### PR DESCRIPTION
**Pull request by ethanresnick**
A number of simplifications. See commit messages for details.

### CODE REVIEW

**Comment by tkellen** [comment]
I'm :+1: to all of this except hiding the sidebar. I think it should just move to the top of the page. That being said, it disappears on the current site, so this isn't making things any worse. @dgeb?

**Comment by ethanresnick** [comment]
> I think [the sidebar] should just move to the top of the page.

Totally agree that we should do our best to always keep the sidebar's key info visible, and I can make more tweaks later with that aim (like moving it to the top or similar). For now, this is just meant to be a first step in that direction by hiding the sidebar in fewer cases than we do currently.

**Comment by ethanresnick** [comment]
@dgeb Are you ok with me merging this?

**Comment by dgeb** [comment]
Sure @ethanresnick - thanks for doing this cleanup :+1:

**Comment by ethanresnick** [comment]
Cool :+1:

**Pull request merged**
