### PR TITLE
Reword singular -> individual and plural -> collection.

### PR DESCRIPTION
**Pull request by dgeb**
This clarifies that collections can contain any number of resources,
and that different endpoints will always return or expect an
individual resource vs. a collection of resources.

### CODE REVIEW

**Comment by BRMatt** [comment]
:+1:

**Comment by whatthewhat** [comment]
@dgeb this does read clearer :+1:

**Comment by dgeb** [comment]
@BRMatt @whatthewhat thanks for confirming! 

@steveklabnik please merge if you agree.

**Comment by steveklabnik** [comment]
Seems good, thanks. :)

**Pull request merged**
