### PR TITLE
Added JSONAPI::Utils gem to the list of Ruby server libraries

### PR DESCRIPTION
**Pull request by tiagopog**
Added [JSONAPI::Utils](https://github.com/b2beauty/jsonapi-utils) gem to the list of Ruby server libraries.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Can you move this to the end please? We've done chronological ordering, historically.

**Comment by tiagopog** [comment]
Sure.

**Comment by steveklabnik** [comment]
Thanks so much!

**Comment by tiagopog** [comment]
Thank you! Cheers!

**Pull request merged**
