### PR TITLE
New visual design including document outline navigation

### PR DESCRIPTION
**Pull request by wvteijlingen**
Pull request for https://github.com/json-api/json-api/issues/527. There are probably still some things to tweak.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thank you so much! 

Open source + design is always hard, so I do want to say that while I think this is certainly a big improvement, we may still end up changing things a bit, okay? I was already talking with some people about some things when this was proposed.

I'm gonna wait to see what others say before I click the button, but :+1: from me, and thank you so much again!

**Comment by wvteijlingen** [comment]
No probs, as long as it is an improvement ;).

The look and feel is still pretty generic so it would be nice if someone with more time and inspiration could create some real recognizable branding for the spec.

**Comment by dgeb** [comment]
Thanks again for your work here @wvteijlingen! Like I've said, I really like the layout changes. I just want to tweak the styling a bit before merging. It will be great to launch 1.0 with a fresh coat of paint!

**Comment by dgeb** [comment]
I am in the process of cherry-picking a number of these commits into a new branch featuring many of the elements from @wvteijlingen's design refresh.

**Comment by dgeb** [comment]
Closed via #629. Thanks again for all your work @wvteijlingen!

**Pull request closed without merging**
