### PR TITLE
switch to ansible based deployment to ec2 server

### PR DESCRIPTION
**Pull request by tkellen**
wip

### CODE REVIEW

**Comment by tkellen** [comment]
Now live on http://ec2-52-7-201-218.compute-1.amazonaws.com.

**Comment by dgeb** [comment]
Lookin' good :smiley_cat:

**Comment by jelhan** [comment]
@dgeb Is deploying the specification website on AWS EC2 still a target? GitHub Pages seem to have worked very well so far - without introducing the need to maintain servers. I'm wondering if we could close this one.

**Comment by auvipy** [comment]
IMHO, using ansible for a single site and single server is a overkill. github page is great. but if a server is still needed, fabfile is simpler option

**Comment by dgeb** [comment]
This PR is very out-of-date at this point. Current plan is to stick with Github Pages.

**Pull request closed without merging**
