### PR TITLE
Add response status for POST with inexistent related resource.

### PR DESCRIPTION
**Pull request by beauby**
related: #1033

### CODE REVIEW

**Comment by dgeb** [comment]
I agree that this should be spelled out under creating resources, as it is under updating resources (see http://jsonapi.org/format/#crud-updating-responses-404).

We need to decide if this should land in 1.0, 1.1, or both.

**Comment by beauby** [comment]
Anything more I can do to help on this one?

**Comment by dgeb** [comment]
@beauby I've labeled this as needing further discussion because of the MUST.

**Comment by beauby** [comment]
Fair enough – my understanding was that this was highly implied by the spirit of the spec, but forgotten to be clearly spelled out.

**Comment by dgeb** [comment]
I agree. I think this change is entirely consistent with the "updating resources" section, and I am not really in favor of downgrading the MUST because its omission was just an oversight.

**Comment by ethanresnick** [comment]
I  trust @dgeb's judgement re adding the MUST.

Re landing in 1.0, 1.1 or both...to date, we've been pretty loose about backporting things to 1.0, and I don't think that's been a problem. If we want to get stricter at some point about the published versions being immutable artifacts, we can, but I'm not sure what the value of that would be now.

Regardless, @beauby please update this pr so that it changes the normative-statements.json files as well. (See e.g. #1102.)

**Comment by beauby** [comment]
@ethanresnick Done.

**Comment by dgeb** [comment]
@beauby please update _format/1.1/index.md as well

**Comment by beauby** [comment]
@dgeb Done as well.

**Comment by dgeb** [comment]
@beauby Thanks again. LGTM.

@ethanresnick Please review.

**Comment by ethanresnick** [comment]
LGTM too. Merged! Thanks @beauby

**Pull request merged**
