### PR TITLE
Deprecate existing extensions

### PR DESCRIPTION
**Pull request by ethanresnick**
This follows a conversation with @dgeb today. The thinking is that keeping the old extensions, and the old negotiation rules, online does more harm than good, as we don’t want people to use them anymore nor do we want to support them going forward.

### CODE REVIEW

**Comment by dgeb** [comment]
LGTM :+1:

**Comment by galiat** [comment]
@ethanresnick - I'm glad you updated the docs since I was about to start implementing the now-deprecate extensions. I'm curious what the plan moving forward is. Is there some place I could follow along with the discussion?

**Comment by ethanresnick** [comment]
Yes, in #957

**Comment by ethanresnick** [comment]
Yes, in #957

**Comment by ethanresnick** [comment]
Yes, in #957

**Pull request merged**
