### PR TITLE
Use '201 Created' HTTP status

### PR DESCRIPTION
**Pull request by lukfugl**
Continued from https://github.com/json-api/json-api/pull/25 with rebase and new commit to incorporate the final comments from that PR.

### CODE REVIEW

**Comment by lukfugl** [comment]
@brixen: don't merge this quite yet; it's a new version from what was being discussed on #25 and I'd like @steveklabnik's and @b's feedback

**Comment by brixen** [comment]
@lukfugl I shall tread carefully. :) Thanks for opening the new PR.

**Comment by steveklabnik** [comment]
@lukfugl is this good now?

**Comment by lukfugl** [comment]
Good as in "I'm happy with it myself", yes. Just asked @brixen to hold off on merge in case you or @b had feedback/editing to suggest.

**Comment by b** [comment]
This looks much better! My only suggestion is that it not say 'PUT
semantics'. The behavior defined is fully compliant with POST. Calling out
PUT makes it sound as if this behavior is abnormal or that POST is not the
right verb to use.

**Comment by lukfugl** [comment]
Should I just drop the parenthetical on sections 4.3.3 vs 4.3.4? If it becomes a common concern of implementers we can elaborate with more space in the FAQ.

**Comment by b** [comment]
I like that better.

**Comment by steveklabnik** [comment]
Awesome. Thanks so much for both of your work on hammering this out.

**Pull request merged**
