### PR TITLE
Remove not maintained DRF-JSON-API

### PR DESCRIPTION
**Pull request by areski**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This project had a commit yesterday?

**Comment by areski** [comment]
It might be confusing cause in the patch I removed the word `(also)` on the active project, if you recheck carefully the diff, you will notice that I removed drf-json-api (on github https://github.com/kevin-brown/drf-json-api) which clearly state that is not maintained.

**Comment by steveklabnik** [comment]
Ah ha! Yes, I clicked the wrong link, sorry! :)

**Comment by areski** [comment]
Thanks :)

**Pull request merged**
