### PR TITLE
Clarify the role of id keys within the URL-based JSON API

### PR DESCRIPTION
**Pull request by andrewsardone**
This comes off of a discussion in json-api/json-api#179 and @steveklabnik's [call for a PR](https://github.com/json-api/json-api/pull/179#issuecomment-32909054).

I'm not sure if the additions align with what the team had in mind, but I wrote down [my earlier thoughts](https://github.com/json-api/json-api/pull/179#issuecomment-32897319) that are based on some experiences implementing a URL-based JSON API.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Thanks for putting this together!

I do like this, unsure about the MUST, though.

**Comment by andrewsardone** [comment]
I'd be interested to hear your reservations on the MUST.

I think all documents need to have _some_ kind of identity, if only for a consumer to map it to some in-memory model, or some row in a database somewhere. I like that this identify is explicit, and qualified with some kind of rule (unique to the document type, or more preferably, a GUID).

Given this common case, I think it makes the most sense to just set up the convention (across both ID-based and URL-based specs) to _always_ have an `id`.

**Comment by dgeb** [comment]
This seems good in general but I would not change MAY to MUST either.

Examples of read-only data that should not require assignment of an arbitrary server-side id include: auto-suggest data (e.g. names starting with "Ab..."), enum-like data (e.g. U.S. states), and raw data (e.g. poll statistics).

**Comment by andrewsardone** [comment]
Then why the [MUST in the ID-based format](https://github.com/json-api/json-api/blob/b4a65c1ba685b86c5ddf9587a7866012aec81622/format/index.md#singular-resources)? Is this an oversight?

I think your examples are good, but if they were treated as singular resources I'd still give them an ID. How else would I link an enum-like value as a to-one relationship off of some resource? For raw statistics, they'd probably be wrapped within some parent resource, like a `pollResults` (which I would give an ID).

**Comment by dgeb** [comment]
@andrewsardone Good catch. We should be consistent about MUSTs. And I don't think we should make that decision until we clarify how raw data should be returned alongside (or embedded in) "normal" documents.

**Comment by andrewsardone** [comment]
@dgeb, so for the time being you would like me to revert the MUST back to a MAY, but leave the note?

**Comment by dgeb** [comment]
@andrewsardone that would be great, and I'll merge right away. It would also be great if you could open another issue regarding the inconsistency between MUST and MAY in the two formats so that we can resolve it separately. Thanks much!

**Comment by andrewsardone** [comment]
Okay, I have rebased-out the MUST.

**Comment by dgeb** [comment]
Perfect - thank you!

**Pull request merged**
