### PR TITLE
Clarify when default fieldsets should be returned.

### PR DESCRIPTION
**Pull request by dgeb**
Also, changed "A server" to "The server" in a couple places for
consistency with the "Inclusion of Related Documents" section.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'd actually prefer "a server" everywhere.

I'm not 100% sure this is clarifying; what does 'unsorted' mean? If it happens to be sorted via some metric, is that bad?

**Comment by dgeb** [comment]
@steveklabnik - I've just removed the "a" / "the" changes. My point was to be consistent with the other "Inclusion of Related Documents" section that I wrote, but I will address these reference changes in a separate PR. I'm not crazy about the way a/the server is referenced repeatedly.

You mention "unsorted", which is not in this change. Are you just providing an example of a default? I actually touch on sorting defaults #148.

As for this particular change: @wycats suggested I add something about defaults, but didn't give specifics. Let's review with him to see if this covers his intentions.

**Comment by steveklabnik** [comment]
Sorry, I read 'unfiltered' and then typed 'unsorted.'

**Comment by steveklabnik** [comment]
(and I agree they should be consistent, thank you for pointing it out!)

**Comment by dgeb** [comment]
#152 is my attempt to make references to "a server" more readable and consistent.

**Pull request merged**
