### PR TITLE
Updates Markdown code blocks with correct types

### PR DESCRIPTION
**Pull request by jfinkels**
Code blocks for HTTP requests should be of the following form.

``````
```http
GET /articles/1
```
``````

Code blocks for JSON data should be of the following form.

``````
```json
{"key": "value"}
```
``````

### CODE REVIEW

**Comment by bintoro** [comment]
I've been wanting to get rid of `javascript` too.

But some of the payloads contain comments and/or ellipses, and these will be highlighted as invalid syntax if marked `json`. That's the reason for `javascript`. I'm sure this could be addressed through CSS, though.

There are quite a few blocks that contain both HTTP and JSON, and this PR turns them all into `http`. However, the highlighter seems to be smart enough to recognize an HTTP response header and a JSON payload inside a `text` block and format them accordingly. Makes no sense to turn those into `http`.

The magic doesn't apply to request examples, but I think I still prefer `text` — then, at least the code is uniformly non-formatted.

**Comment by tkellen** [comment]
Thanks for taking the time to submit this PR @jfinkels. Would you mind re-basing this and updating to only use `http` in examples where the only content of the block is http?

**Comment by jfinkels** [comment]
Okay, now the pull request only changes HTTP request blocks.

**Comment by tkellen** [comment]
Thanks @jfinkels!

**Pull request merged**
