### PR TITLE
Reindent json properly

### PR DESCRIPTION
**Pull request by amenophis**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Which definition of 'proper' is this? Ie, is this some sort of globally recognized style for formatting?

**Comment by amenophis** [comment]
I just make it more readable. Use Sublime Text indentation.
you could take it or not ;)

**Comment by steveklabnik** [comment]
Fair enough! I was just curious :)

Let's see what others think. We haven't made an explicit judgment about how to format these things.

**Comment by tkellen** [comment]
Six of this half a dozen of the other to me. If we're going to update one we should make them all consistent though.

**Comment by tkellen** [comment]
@dgeb @ethanresnick? If either of you want this, this PR should be updated to include all other examples. I'm indifferent.

**Comment by ethanresnick** [comment]
I'm indifferent too. Maybe not worth the hassle.

**Comment by tkellen** [comment]
I appreciate the effort @amenophis, but I think we're going to pass on this for now.

**Pull request closed without merging**
