### PR TITLE
Introduce support for specifying sort order.

### PR DESCRIPTION
**Pull request by dgeb**
Describes how a server may optionally support requests for
primary and related documents to be sorted according to
specific criteria.

### CODE REVIEW

**Comment by steveklabnik** [comment]
I'm not sure this needs to be in the main spec, this is an example of something that should probably be in a profile.

That said, I can _also_ see it going in the main spec, so I'm not going to close this just yet.

**Comment by dgeb** [comment]
@steveklabnik Let me back up and provide some background on this and my other recent PRs.

The goal of JSON API is "to support a smart client who wishes to build a data-store of information". Without providing guidelines for common use cases such as including related records, customizing fieldsets, sorting, filtering, and even pagination, there is a limit to how "smart" we can build client and server frameworks that consume and produce this media type. I'm in favor of providing these guidelines, while ensuring that each is optional by specifying them very liberally with MAYs.

I agree that a server's specific implementation of these guidelines belongs in a profile. For instance, some servers may not support sorting at all, while others may support sorting for only the primary document, while still others may support sorting for only specific fields. As long as client and server frameworks know how to comply with each of these conditions, they can still have the intelligence to work with them rather than leaving all these concerns to ad hoc implementations.

**Comment by wycats** [comment]
I'm in favor of these as **MAY**s that have good defaults if an endpoint does not support them.

**Comment by steveklabnik** [comment]
Absolutely, it's a balance.

**Comment by dgeb** [comment]
@steveklabnik - how are you feeling about this sorting PR now that **MAY** has been used extensively?

**Comment by steveklabnik** [comment]
Feeling good.

**Comment by dgeb** [comment]
Woot - the PR backlog is clear :)

**Comment by steveklabnik** [comment]
:heart: thanks for all the recent work

**Pull request merged**
