### PR TITLE
Applying to add new php library

### PR DESCRIPTION
**Pull request by elb98rm**
Applying to add new php library: https://github.com/floor9design-ltd/json-api-formatter

Info: 
* 100% unit tests
* CI implemented
* 6 use months in production environments in multiple projects
* actively maintained

### CODE REVIEW

**Comment by jelhan** [comment]
Thanks a lot for opening this PR. I'm sure it's a great library but how is it related to JSON:API specification? I skimmed over the readme and didn't found the specification to be mentioned at all.

**Comment by elb98rm** [comment]
Not sure I understand the feedback. Can you help explain?

Just to be clear: It's not about the specification - this is a library allowing people to import/export their data to/from JSON API.

Note that many others in the list do the same, for example:

* [jsonapi-consumer](https://github.com/jsmestad/jsonapi-consumer) a ruby library for consuming JSONAPI payloads.

If you want to see if I'm referencing the JSON API spec, it's directly linked (along with a validator) in the testing area.

**Comment by jelhan** [comment]
> this is a library allowing people to import/export their data to/from JSON API.

Are you sure that you included the correct link in the post? It links to `test-data-generator`, which is described as the following:

> A class for generating simple data, ideal for testing/seeding or other random code requirements.

Would be great if you could update the title of this pull request as well to reflect what is it doing.

**Comment by elb98rm** [comment]
D'oh

That's a DIFFERENT repo I'm working on - must have been a copy paste issue!
Updating this now.

**Comment by elb98rm** [comment]
Corrected repo link in request above. Note that the repo link in the code was correct.

**Review by jelhan — APPROVED** [review]
Thanks a lot for fixing the link in PR description. To be honest I haven't had a look in the commit before.

Looks good to me. 👍 

I don't have merge permissions myself. Need to wait for @dgeb to give it a final review and merge.

**Comment by dgeb** [comment]
Looks good to me as well. Thanks @elb98rm for the library and @jelhan for the review!

**Pull request merged**
