### PR TITLE
Added https://jsonapi-validator.herokuapp.com service to implementations

### PR DESCRIPTION
**Pull request by karthikselva**
- This service can be used to enter/edit any JSON response and verify whether it follows jsonapi.org specification or not.
- We are using this service throughout our organization during API design phase and thought this might help other people in the community as well
- Added jsonapi-validator service to Related tools section of
  jsonapi.org/implementations
- Placed under Implementations > Related Tools > Playground
- Link to the service is https://jsonapi-validator.herokuapp.com

### CODE REVIEW

**Comment by evolve2k** [comment]
This looks good to me. 
Ready to merge.

**Comment by bf4** [comment]
Is it open source?  (Like, can I see if the validations look right to me? ref https://github.com/json-api/json-api/issues/1098 )

What's the license?

**Comment by evolve2k** [comment]
Within the validator it links to the github repo with the underlying code available in an open public repo, so I'd say yes it is. Repo here - https://github.com/karthikselva/jsonapi-validator-service.

For specific licence you might want to just raise an issue on the project itself.

Im guessing your comments aren't blocking concerns with regards to including a link to this resource in the project help files is it?

This is still a simple merge and a useful link to share under resources in my opinion.

**Comment by karthikselva** [comment]
@bf4 Added MIT License, please let me know if I am missing something

**Comment by bf4** [comment]
@evolve2k @karthikselva (I don't have commit. was just asking)

**Comment by bf4** [comment]
Is this just a web app that [applies a json schema validator to the schema file](https://github.com/karthikselva/jsonapi-validator/blob/834c677cf5e619ffb7559343be9ee53a2fe78621/schema/schema.json) [in this repo](https://github.com/json-api/json-api/blob/78312120d18ed30c026836eaffd5422eafae6945/schema)?  That schema is neither complete nor authoritative. (That's why I was interested in the source.   No one has published anything authoritative or comprehensive yet.)

**Comment by karthikselva** [comment]
@bf4 [This](https://twitter.com/steveklabnik/status/741345411416358912) is where it started. I am not sure when the schema will be comprehensive. Let me know once the schema is published authoritatively so that I can update and send another PR, or if you think I can do any further steps on getting the schema comprehensive I can take that as well. Thanks !

**Comment by bf4** [comment]
re: authoritative https://github.com/json-api/json-api/pull/440#issuecomment-151013219 and ref: some earlier discussion of the schema https://github.com/json-api/json-api/issues/867

**Comment by karthikselva** [comment]
@bf4 Cool thanks 👍

**Comment by evolve2k** [comment]
Thanks for the PR @karthikselva and the discussion @bf4.

I'm thinking the question of what constitutes a proper validator requires ongoing discussion and is probably better suited for discussion elsewhere.

Backing @steveklabnik's tweet comments, I can't see any issue with adding this link under related tools playground.

Considerations for how to best validate JSONAPI spec are defintley of interest to me.
May I suggest we retake up discussion on the forums, maybe these threads?

http://discuss.jsonapi.org/t/how-to-validate-the-json-api-format/147
http://discuss.jsonapi.org/t/development-of-a-validation-tool/416

@bf4 it might even be better to pose your own question on the forums so we can best narrow in on how to progress this.

Admins, lets get this link merged!

**Comment by dgeb** [comment]
After all the discussion, I forgot to come back and merge this. Sorry for the delay. And thanks for great validator! 💯

**Comment by evolve2k** [comment]
All good. Thanks for being a fab open source peep. 🤘

**Pull request merged**
