### PR TITLE
FAQ: New Q/A: How discover resource capabilities?

### PR DESCRIPTION
**Pull request by diosney**
Add a new Q/A to let implementors know how they can provide resource discovery capabilities.

Maybe this could be moved to standard itself?

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is certainly a FAQ-level thing, as it just repeats what's in RFC 2616.

**Comment by diosney** [comment]
I agreed. Nice I pushed to the correct section :)

So, what do you think? It worth to be included?

When I checked the issues I found one guy that requested something like resource discovery capabilities but maybe is so simple that it doesn't worth the space.

**Comment by steveklabnik** [comment]
I like having it, but I'm not sure why the bottom two sentence parts are in bullet points. Maybe just as a regular sentence? Also, linking to the errors issue would be good :)

**Comment by diosney** [comment]
The bullet points were just to standout them. I removed them in a new commit.

The **Errors** debate is in #7 (already linked in Q/A).

**Comment by steveklabnik** [comment]
Looks great, thanks for putting up with the bikeshed. :ship: :heart: :confetti_ball:

**Comment by diosney** [comment]
Awesome!

Bikeshed (and  anti-bikeshedding at the site home) are referring to [Parkinson's law of triviality](http://en.wikipedia.org/wiki/Bikeshed)?

**Comment by diosney** [comment]
Ha! I understand now after reading the law lol!

Maybe I can link those words in the site home so anybody can look quickly at the term in Wikipedia?

**Comment by steveklabnik** [comment]
Naw, we don't need a definition of it here. heh.

**Comment by diosney** [comment]
Hehe, seems that I got caught bikeshedding :D ha!!

Okey, I won't continue spamming here :)

**Pull request merged**
