### PR TITLE
Error objects: `parameter` only refers to URI query parameters

### PR DESCRIPTION
**Pull request by ethanresnick**
There was a bit of confusion in #828 about what the `"parameter"` member in error objects referred to. This is a very tiny PR that just clarifies that "parameter" means a URI query parameter, not a parameter in the sense of any payload data that might affect the request.

### CODE REVIEW

**Comment by bf4** [comment]
:+1: :smile:

**Comment by ethanresnick** [comment]
@json-api/owners This good to merge?

**Comment by tkellen** [comment]
:+1:

**Comment by ethanresnick** [comment]
Cool beans.

**Pull request merged**
