### PR TITLE
Asynchronous Processing Recommendation tweaks

### PR DESCRIPTION
**Pull request by nonsensery**
#### What's this PR do?

Fixes some formatting issues in the Asynchronous Processing section of the Recommendations page, and expands on it a little.
#### Where should the reviewer start?

All of the changes are confined to this one section. I started out just looking to fix some formatting issues in this section, and the rest of the changes flowed from that. Here's a list of the changes I've made:
- Combined the "queue job" response body into the HTTP request code block.
- Reformatted the "queue job" response data (and removed an extra `}`).
- Changed the "queue job" `type` and URL slug to `queue-jobs` so that it's more JSON-API-like.
- Added sample HTTP requests, and updated the surrounding text to be more like the stuff on the Specification page.

And here's a screenshot of the rendered page:

screen shot 2015-11-30 at 11 25 13 am

### CODE REVIEW

**Comment by ethanresnick** [comment]
I'm :+1: on all these changes. Can you just squash down the commits and then I'll merge it in?

**Comment by nonsensery** [comment]
Squashed.

FYI: I think there will be a small conflict between this PR and #930.

**Comment by ethanresnick** [comment]
Awesome, thanks!

**Comment by benoittgt** [comment]
Thanks @nonsensery

**Pull request merged**
