### PR TITLE
Design refresh

### LINKED ISSUE #527: New visual design including document outline navigation
I found the spec hard to read because everything is one page without any document outline or other navigation. When trying to add a sidebar I got the idea to refresh the whole design. Now I am by no means a great designer, but this is what I quickly whipped up.

I've added a (fixed) sidebar that contains a document outline for some pages. This is generated with JavaScript, which is the only way to do it using Github pages afaik.

The design is still pretty bland, but if you guys think this is an improvement, I'll make a pull request for it. The HTML and CSS is already done. I think for the 1.0 release this will be a nice refresh.

json-api home
json-api format
json-api format scrolled

### PR DESCRIPTION
**Pull request by dgeb**
This PR is based on @wvteijlingen's excellent work in #531. The original color scheme and logo have been maintained, although they have been refined somewhat.

One of the major benefits of this work is the introduction of a sidebar for document navigation.

I'm going to merge this ASAP in order to give us time to refine the design and fix any glitches before 1.0. Please review!

[Closes #527 and #531]

### CODE REVIEW

**Comment by ethanresnick** [comment]
@dgeb This is awesome!

Thanks again @wvteijlingen!

**Comment by steveklabnik** [comment]
:heart_eyes:

**Comment by hhware** [comment]
Looks much more elegant now, kudos to everyone involved!

**Comment by joananeves** [comment]
New design is great but there's a problem on sidebar, if the window is not big enough, the sidebar content is appearing incomplete and above the footer.
screen shot 2015-05-20 at 10 55 17

**Comment by wvteijlingen** [comment]
Great to have this merged in! Good point on the sidebar @joananeves. We could make it scrollable or perhaps add a breakpoint on window height to make it non-fixed on small viewports.

**Pull request merged**
