### PR TITLE
"Must" in non-normative notes

### PR DESCRIPTION
**Pull request by hhware**
Does it actually make sense there? IMHO, either "must" should be downgraded to a softer term or non-normative note should be upgraded to a constraint.

### CODE REVIEW

**Comment by bintoro** [comment]
I see no reason to avoid words like "must". The specially formatted keywords exist for a purpose.

As for why some things are written as non-normative segments: I believe this is based on having just one normative clause per rule. Any explanations that repeat or clarify a previously stated rule are expressed in a non-normative way.

I agree that formal MUSTs in non-normative notes are not ideal. My preferred approach would be just to turn each of them into an informal "must".

**Comment by tkellen** [comment]
:+1: to these edits as is. I agree that 2119 keywords do not belong in non-normative notes (I have updated a few instances of this as well).

**Comment by hhware** [comment]
@bintoro I personally do not quite understand what is the meaning of plain-text "must", whether in the spec or in notes. How should I read it? Is it a constraint or not? If not, why use "must"?

Perhaps it would make sense to convert all verbs covered by RFC2119 to boldfaced all-caps keywords? The RFC specifies how these words should be read: any document can just refers to it and be done with this formality. If non-RFC versions of these words are used, what are they supposed to mean, where is the difference between RFC and non-RFC versions defined? Why introduce this confusion in the first place?

If for some reason the spec wants to stay intentionally ambiguous about something, some synonym could be used ("ought to", "can"?), although I personally fail to see a reason why this **MUST** be necessary...

FYI, a PR on a similar issue: #474

**Comment by bintoro** [comment]
@hhware The plaintext "must" carries the normal meaning of the word; it's a requirement. But the lack of a formal keyword is an indication to the reader that the statement doesn't introduce a _new_ normative requirement. That is, the sentence can be skipped without loss of critical information.

Isn't it good that we can liberally add explanatory statements and notes without bloating the text with redundant normative clauses? IMO it's silly to have a number of normative rules for the exact same thing. It has nothing to do with "intentionally ambiguous".

**Comment by hhware** [comment]
> Isn't it good that we can liberally add explanatory statements

@bintoro, thank you for the explanation, got it now. 

(I still think that all editions suggested here are appropriate.)

**Comment by hhware** [comment]
I would like to request to consider this for 1.0.

**Comment by hhware** [comment]
A humble reminder: this issue is still awaiting fulfillment of @dgeb's [promise](https://github.com/json-api/json-api/issues/507#issuecomment-86633286).

**Comment by hhware** [comment]
Rebased this PR. Two items are left out of initial three.

**Comment by tkellen** [comment]
:+1: from me @dgeb?

**Comment by dgeb** [comment]
Thanks @hhware!

**Comment by hhware** [comment]
I have a suspicion that this and 3 preceding merges were lost because of forced push to gh-pages...

**Comment by tkellen** [comment]
Checking on this briefly.

**Comment by tkellen** [comment]
You're correct @hhware. I'm on my wife's computer today (mine is being repaired) and her git config is set to push matching, not push simple. My force pushes without specifying the top-level-attributes branch force pushed over gh-pages. Fixing this now.

**Pull request merged**
