### PR TITLE
Added Elide to Java implementations.

### PR DESCRIPTION
**Pull request by DennisMcWherter**
We recently released Elide which is a web framework that uses JSON API for its interchange format.

### CODE REVIEW

**Comment by ethanresnick** [comment]
Hi @DeathByTape 

We're working on an objective way to order the implementations in each section (see #733), but, until that's ready, chronological ordering is what we've been going with so as to not play favorites. 

Can you please update this PR to put Elide at the end of the list, rather than at the top, and then I'll give this a merge.

**Comment by DennisMcWherter** [comment]
Absolutely! Sorry I didn't mean any harm; I was just going alphabetically :) I'll rebase in a moment.

**Comment by DennisMcWherter** [comment]
Updated!

**Comment by ethanresnick** [comment]
No worries, and thanks! Merged.

**Pull request merged**
