### PR TITLE
Link to the json-api-vanilla Ruby gem

### PR DESCRIPTION
**Pull request by espadrine**
Adds link to the [`json-api-vanilla`](https://github.com/trainline/json-api-vanilla) gem within the implementations page.

### CODE REVIEW

**Comment by dgeb** [comment]
@espadrine would you mind moving this to the bottom of the list? We're trying to keep the lists roughly chronological.

**Comment by espadrine** [comment]
@dgeb Sure thing! Done.

**Comment by steveklabnik** [comment]
Thank you!

**Comment by espadrine** [comment]
Thanks a lot!

**Pull request merged**
