### PR TITLE
Add a Vala implementation based on JSON-GLib

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by dgeb** [comment]
Thanks!

**Comment by arteymix** [comment]
No problems! It's powering http://mirbooking.major.iric.ca/ by the way :)

**Comment by dgeb** [comment]
@arteymix nice! Would you mind posting a link over in https://github.com/json-api/json-api/issues/825 ?

**Comment by arteymix** [comment]
@dgeb done!

**Comment by dgeb** [comment]
@arteymix thank you! 💯

**Pull request merged**
