### PR TITLE
Supply a json-schema of the json-api

### PR DESCRIPTION
**Pull request by kjg**
pulled from https://github.com/json-api/parser-ruby/blob/master/lib/json/api/schema.json

### CODE REVIEW

**Comment by steveklabnik** [comment]
Why duplicate this across the two repositories?

Also, since JSON Schema isn't powerful enough to represent all of JSON API, I'm a little averse to actually making it so prominent.

**Comment by kjg** [comment]
If this makes it into jsonapi.org I would expect the other repo to migrate
to using this one.

What can't json schema represent about json api? This pr already improves
upon the other's coverage and there is still way more we can add. I hope to
do just that if I can get the buy in.

Making it canonical means there is a sanctioned, maintained schema people
can validate responses against instead of some githubraw url.

**Comment by steveklabnik** [comment]
Thanks! I'd love to merge this, but it's now out of date. Could you rebase, please?

**Comment by kjg** [comment]
Sorry about that. Rebased.

**Comment by steveklabnik** [comment]
No worries. Thanks so much!

**Pull request merged**
