### PR TITLE
add typescript section; add ts-jsonapi

### PR DESCRIPTION
**Pull request by mohuk**
ts-jsonapi is a port of jsonapi-serializer written purely in Typescript with a minor additions

### CODE REVIEW

**Comment by steveklabnik** [comment]
Nice! Could you switch the order of the two though please? We keep the list in chronological order.

**Comment by mohuk** [comment]
done

**Comment by abdulhaq-e** [comment]
Could you also please move `ngrx-json-api`.

**Comment by remmeier** [comment]
you may also add katharsis as java client library, most recent releases support both client and server use

**Comment by mohuk** [comment]
@remmeier there should be another PR/Issue for the Java libs I believe :)

**Comment by dgeb** [comment]
@steveklabnik this LGTM now. What do you think?

**Comment by dgeb** [comment]
Sorry to take so long to merge this. And thanks again for the contribution!

**Pull request merged**
