### PR TITLE
add creative commons c0 license

### LINKED ISSUE #283: licensing?
Obviously CC0 or something like it, but we should maybe be explicit about this.

### PR DESCRIPTION
**Pull request by tkellen**
closes gh-283

### CODE REVIEW

**Comment by dgeb** [comment]
:+1:

**Comment by dgeb** [comment]
@tkellen can you rebase please so we can merge before 1.0?

**Comment by tkellen** [comment]
Hows that?

**Comment by dgeb** [comment]
thanks :+1:

**Pull request merged**
