### PR TITLE
when creating a new resource, wrap the document in an array.

### PR DESCRIPTION
**Pull request by mikaa123**
singular resource retrieval wraps the resource's representation document in an array, like so:

```
{
  "posts": [{
    // an individual post document
  }]
}
```

posting a new resource to the server with a client-side generated id also uses an array:

```
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": [{
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }]
}
```

in order to stay coherent, I suggest to wrap the content of the new document in an array when creating a new resource:

```
POST /photos
Content-Type: application/json
Accept: application/json

{
  "photos": [{
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }]
}
```

this would also allow posting multiple new documents at once.

### CODE REVIEW

**Comment by lukfugl** [comment]
Is gh-pages the right branch to be targeting with pull requests? I thought it was master...

**Comment by chrishunt** [comment]
Closes #59

**Comment by steveklabnik** [comment]
Yes, it is now. There's only the gh-pages branch. We moved from Middleman to Jekyll, so now we don't need a separate compilation step, every push builds.

**Comment by steveklabnik** [comment]
Thanks.

**Comment by lukfugl** [comment]
Ah, good to know. Should I redo PR #62 against gh-pages then? That one was against master...

**Comment by steveklabnik** [comment]
I merged it in before we did the switch, no?

**Comment by lukfugl** [comment]
Doesn't look like it. It was merged two days ago, and the gh-pages branch's updating/index.md doesn't appear to have the modifications from #62.

**Comment by steveklabnik** [comment]
@brixen? I thought I saw a back port.
—

**Comment by chrishunt** [comment]
@steveklabnik @lukfugl The changes _are_ in gh-pages:

https://github.com/json-api/json-api/blob/gh-pages/updating/index.md#response

**Comment by brixen** [comment]
@lukfugl I ported it manually to gh-pages because @steveklabnik had already merged the PR on master. Could you double check it please?

**Comment by lukfugl** [comment]
@brixen: will do (@chrishunt: hadn't seen the backport yet (did it exist?) when I wrote that :smiley:)

**Comment by lukfugl** [comment]
yup. looks good. I guess I forgot to fetch before checking my local copy of json-api:gh-pages; that'll teach me to not double check my sources before making comments like that :) sorry for the confusion.

**Comment by brixen** [comment]
@lukfugl no worries! Thanks for double-checking the content. Apologies for all the confusion as I migrated to gh-pages.

**Pull request merged**
