### PR TITLE
Clarify scope of type/id uniqueness

### PR DESCRIPTION
**Pull request by ethanresnick**
This is a PR to clarify/close the issue raised in #578.

### CODE REVIEW

**Comment by dgeb** [comment]
This may seem a bit pedantic, but I don't think that the spec normatively defines an "API". There are concepts that imply such a definition, such as a "server" needing to respond to `self` and `related` links.

Maybe this speaks to needing to merge what's implied by "server" and "API"?

**Comment by ethanresnick** [comment]
Good point. Especially if we start thinking about relating resources between APIs, it'll only become more important to be explicit about these definitions somewhere.

Would a sentence like "The set of URIs controlled by a server, or multiple servers acting as one, constitute an API." suffice?

**Comment by tkellen** [comment]
Yes, I think so @ethanresnick.

**Comment by ethanresnick** [comment]
@tkellen Done!

**Comment by dgeb** [comment]
> @tkellen Done!

@ethanresnick not seeing the change - did you forget to push?

**Comment by ethanresnick** [comment]
D'oh. I accidentally pushed to a branch I have going for something else. Fixed.

**Comment by tkellen** [comment]
:+1: from me

**Comment by dgeb** [comment]
Thanks @ethanresnick!

**Pull request merged**
