### PR TITLE
Updated version badge styling

### PR DESCRIPTION
**Pull request by wvteijlingen**
Updated the styling of version badge to fit better in the navigation bar. Also increased the mobile breakpoint to accommodate for the version badge.

### CODE REVIEW

**Comment by tkellen** [comment]
Awesome! Could you make it so the background isn't fluid width in mobile sizes?
screen shot 2015-06-03 at 12 57 52 pm

**Comment by wvteijlingen** [comment]
Ah yes, will do!

**Comment by wvteijlingen** [comment]
Updated for mobile viewports.

**Comment by tkellen** [comment]
:+1: looks fantastic, thanks @wvteijlingen!

**Pull request merged**
