### PR TITLE
Add playground website jsonapi.co

### PR DESCRIPTION
**Pull request by sanmak**
- Added website https://www.jsonapi.co/ which is free to use the API to test code. Incorporated inside implementation playground.

### CODE REVIEW

**Comment by dgeb** [comment]
@sanmak this looks like a very useful site for developers, but I don't see any indication that it is specific to the [JSON:API specification](https://jsonapi.org/format/). Am I missing something?

**Comment by sanmak** [comment]
@dgeb Thanks for appreciating. 
And yes it's actually following all JSON API verbs and how's structure should look like. Fetching resources, sorting, filtering, pagination all follow as per mentioned in https://jsonapi.org/format/.

**Comment by dgeb** [comment]
Hmmm, I'm scratching my head here over the examples I've looked at. The media type is `application/json` and not `application/vnd.api+json`, there are extra levels of nesting under `data` (e.g. `data/users`), resource objects don't have `type` members, attributes aren't nested in `attributes`, etc.

For example, on the home page, I see the following response:

```
{
  "success": true,
  "data": {
    "users": [
      {
        "id": 18,
        "createdAt": "2020-01-25T17:03:55.791Z",
        "name": "Edd Quigley",
        "email": "Abdullah_Kirlin19@yahoo.com",
        "phoneNumber": "918-352-7738 x326",
        "about": "Eveniet optio itaque sequi quibusdam. Molestiae sunt molestiae. Optio quo reiciendis et laboriosam voluptatibus tenetur qui vel harum. Ipsam placeat quaerat eligendi. Ratione ex exercitationem totam voluptatum quaerat tempore nostrum sit placeat. Dolor vel quos rerum dolor sit ea mollitia sed explicabo.",
        "url": "http://walter.name",
        "image": {
          "url": "http://lorempixel.com/640/480"
        },
        "address": {
          "city": "South Tiabury",
          "state": "New York",
          "country": "Croatia",
          "latitude": "86.3616",
          "longitude": "51.8145",
          "zipCode": "64591"
        },
        "company": {
          "name": "Krystina Gulgowski",
          "phrase": "Self-enabling radical local area network"
        },
        "finance": {
          "account": "30671941",
          "amount": "444.68",
          "transactionType": "payment",
          "currencyCode": "MGA",
          "currencyName": "Fiji Dollar",
          "currencySymbol": "S/.",
          "bitcoinAddress": "3ACMB2684E5H1AHB2HZAGHCW3A5DYDT6",
          "iban": "PS31M070274700185684860509506",
          "bic": "MFJOETB1"
        }
      },
      {
        "id": 3,
        "createdAt": "2019-10-13T01:15:08.609Z",
        "name": "Geraldine Breitenberg",
        "email": "Euna_Sauer24@hotmail.com",
        "phoneNumber": "826.231.1760",
        "about": "Eligendi non autem ipsum. Voluptatem quia nam velit labore nemo. Optio rerum voluptatem totam quia et. Eum tempora iste ipsum iste officia. Ut ut non fugit atque magnam veniam sit nemo. Corporis reprehenderit voluptatem ipsam.",
        "url": "http://curtis.biz",
        "image": {
          "url": "http://lorempixel.com/640/480"
        },
        "address": {
          "city": "Aylaview",
          "state": "Kansas",
          "country": "Syrian Arab Republic",
          "latitude": "63.6307",
          "longitude": "56.0780",
          "zipCode": "11770"
        },
        "company": {
          "name": "Ila Boyle",
          "phrase": "Phased explicit toolset"
        },
        "finance": {
          "account": "12914791",
          "amount": "258.12",
          "transactionType": "payment",
          "currencyCode": "CUP CUC",
          "currencyName": "Australian Dollar",
          "currencySymbol": "$",
          "bitcoinAddress": "17SJ1N5OW5RU1CFDVC3PHEEN4QWA8",
          "iban": "AZ7080QP55004773034065539015",
          "bic": "TLWIRUS1"
        }
      },
      {
        "id": 35,
        "createdAt": "2019-08-29T15:11:19.918Z",
        "name": "Sheldon Erdman",
        "email": "Patricia.Sporer95@hotmail.com",
        "phoneNumber": "807.338.7022",
        "about": "Laborum velit atque natus quo facere architecto consequatur. Est soluta eum rerum non est laborum eaque rem. Et quo ut ipsam. Veniam deserunt repudiandae dolor quis perferendis. Pariatur autem est nisi unde dolorum libero amet quo. Nam amet aliquid aut ex rerum iure et sunt architecto.",
        "url": "http://jarrell.name",
        "image": {
          "url": "http://lorempixel.com/640/480"
        },
        "address": {
          "city": "Sauerborough",
          "state": "Montana",
          "country": "Seychelles",
          "latitude": "21.8087",
          "longitude": "141.6102",
          "zipCode": "74229-0545"
        },
        "company": {
          "name": "Green Rogahn",
          "phrase": "Cloned demand-driven software"
        },
        "finance": {
          "account": "53809439",
          "amount": "859.46",
          "transactionType": "deposit",
          "currencyCode": "KZT",
          "currencyName": "Moroccan Dirham",
          "currencySymbol": "₫",
          "bitcoinAddress": "1KAL8620D49OVM1RKI3LLBJU7TL3S",
          "iban": "AL5040097004NB877PU590535E65",
          "bic": "SNBEMMY1CAU"
        }
      }
    ],
    "pagination": {
      "total": 35,
      "perPage": 3,
      "currentPage": 1,
      "nextPage": 2,
      "previousPage": 1
    }
  },
  "error": null,
  "adSpace": []
}
```

Should I be looking elsewhere?

**Comment by dgeb** [comment]
Closing for lack of response.

**Pull request closed without merging**
