### PR TITLE
remove unmaintained node.js server library

### PR DESCRIPTION
**Pull request by ghost**
Remove https://github.com/SeyZ/jsonapi-serializer implementation because
it is not actively maintained.
Following the discussion in https://github.com/json-api/json-api/issues/733 and https://github.com/json-api/json-api/issues/1313, I think it would be incredibly helpful to have some way for libraries to prove their adherence to a given version of the specification.

### CODE REVIEW

**Comment by ckeboss** [comment]
Could we replace it with https://github.com/danivek/json-api-serializer

**Comment by dgeb** [comment]
I'm reluctant to remove this library because there's been commit activity within the past two months: https://github.com/SeyZ/jsonapi-serializer/commits/master

Given this, I'd want confirmation from @SeyZ before doing anything.

> Could we replace it with https://github.com/danivek/json-api-serializer

@ckeboss That seems fairly popular and doesn't appear to be a fork of SeyZ/jsonapi-serializer. Perhaps danivek/json-api-serializer should have an entry of its own?

**Comment by ghost** [comment]
I'd second making https://github.com/danivek/json-api-serializer a new entry. Given both have similar goals (framework agnostic), perhaps we could annotate that in their descriptions?

**Comment by ckeboss** [comment]
@dgeb Sure. Perhaps a little emphasis that the names are very similar.

**Pull request closed without merging**
